services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    mem_limit: 256m
    cpus: "0.3"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    mem_limit: 512m
    cpus: "0.5"
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    mem_limit: 256m
    cpus: "0.3"
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka1:29092
    depends_on:
      - kafka1
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    mem_limit: 256m
    cpus: "0.3"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  app:
    build: 
      context: ./readermicroservice
      dockerfile: Dockerfile
    image: readermicroservice:latest
    container_name: reader-app
    mem_limit: 128m
    cpus: "0.2"
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
      - KAFKA_BROKERS=kafka1:29092
    depends_on:
      migrate:
        condition: service_completed_successfully
      kafka1:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network
  
  migrate:
    image: migrate/migrate:4
    volumes:
      - ./readermicroservice/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://myuser:mypassword@db:5432/mydatabase?sslmode=disable",
      "up"
    ]
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge